### ISSUE TITLE
Limit file types for upload

### ISSUE THREAD

**Issue by colin-combe** [Rappsilber-Laboratory/searchSubmit#1]
<a href="https://github.com/lutzfischer"><img src="https://avatars.githubusercontent.com/u/6330440?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lutzfischer](https://github.com/lutzfischer)**
_Friday Mar 25, 2016 at 13:30 GMT_
_Originally opened as https://github.com/martingraham/searchSubmit/issues/1_

----

File types (by extension only)
PeakList/Acquisition:

.mgf
.msm
.apl
.zip
Fasta/sequence files:

.fasta
.txt
Capitalisation should be ignored

**Comment by colin-combe** [comment]
Moved from https://github.com/martingraham/searchSubmit/issues/1

**Comment by martingraham** [comment]
should be done - labls stating which files are accepted, file dialog filters on browsers that supports them, uploader kicks out any rogues that sneak through

**Comment by martingraham** [comment]
closing
