### ISSUE TITLE
Switching from last  search to default parameters does not clear custom settings

### ISSUE THREAD

**Issue by lutzfischer** [Rappsilber-Laboratory/searchSubmit#6]
Notes are also not cleared - but I think that could be sold as feature.

**Comment by martingraham** [comment]
yeh, if notes/customsettings are empty it doesn't overwrite the existing ones in the form. Easy enough to change tomorrow.

**Comment by martingraham** [comment]
should be fixed now

**Comment by lutzfischer** [comment]
Can you flag if there are manual entries and only overwrite if there 
where no manual entries?

On 05/04/16 16:59, Martin Graham wrote:
>
> yeh, if notes/customsettings are empty it doesn't overwrite the 
> existing ones in the form. Easy enough to change tomorrow.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/Rappsilber-Laboratory/searchSubmit/issues/6#issuecomment-205869723>
>


-- 
Lutz Fischer
lfischer@staffmail.ed.ac.uk
+44 131 6517057


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by martingraham** [comment]
done
